apiVersion: v1
kind: Service
metadata:
  name: gowebserver-service
  labels:
    app: gowebserver
spec:
  selector:
    app: gowebserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer