apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  labels:
    app: goserver
spec:
  selector:
    app: goserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer